export const RECEIVE_DAILY_MATCHES = 'RECEIVE_DAILY_MATCHES';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const NEW_USER = 'NEW_USER';
export const ADD_MEMBER_TO_LEAGUE = 'ADD_MEMBER_TO_LEAGUE';
export const ADD_MEMBER_TO_BONSPIEL = 'ADD_MEMBER_TO_BONSPIEL';
